### PR TITLE
add "Hyperland" screening proposal

### PR DESCRIPTION
**Pull request by nchase**
# Douglas Adams's _Hyperland_

In 1990, Douglas Adams of _The Hitchhiker's Guide To The Galaxy_ series fame writes and presents a "fantasy documentary" about hypertext and surrounding technologies. This was the same year the first web browser was released. _Mosaic_ wasn't released until 1993, so this is very early/nascent stuff and (I hear) it predicts the modern web with remarkable accuracy.

This promises to be fun and maybe a little bit strange. Let's go back to 1990 for a little under and hour and get weird!

### CODE REVIEW

**Comment by nchase** [comment]
how will anyone be able to resist this?

**Comment by commandline** [comment]
:shipit:

**Comment by nmielnik** [comment]
Merging this in so external people can see it

**Comment by nchase** [comment]
Good call :thumbsup:

**Pull request merged**
