### PR TITLE
Friday Aug 28th Screening Proposal: James Mickens - Computer Security

### PR DESCRIPTION
**Pull request by GWShark0**
[Not Even Close The State of Computer Security](https://youtu.be/O0uCeq3vb34) - James Mickens (~30 mins)

[](https://youtu.be/O0uCeq3vb34)

If you haven't yet read/witnessed content by James Mickens, you really should. He's hilarious.

### CODE REVIEW

**Comment by nchase** [comment]
:clap:

**Comment by adamwadesmith** [comment]
This link includes the slides: https://vimeo.com/135347162 .

Date: Tue, 25 Aug 2015 09:44:15 -0700

**Comment by patrick-webs** [comment]
@ayobami14 and I are also giving a talk on Undo / Redo in Tower at this time Friday although it's not on the lunch schedule since only watchmen & architects team members and a few others were on the invite.

**Comment by GWShark0** [comment]
@patrick-webs ah that's my bad, I'll submit a change to move this to the Friday after next (9/4).

**Pull request merged**
